# Generated by Django 5.0.6 on 2024-06-06 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_juego', models.CharField(max_length=100, verbose_name='Nombre')),
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(choices=[('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3')], max_length=3)),
                ('precio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('descripcion', models.TextField()),
                ('foto_juego', models.ImageField(upload_to='juegos', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Probar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proando', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nomb_usuario', models.CharField(max_length=13, verbose_name='Nombre de usuario')),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('O', 'OTRO'), ('F', 'FEMENINO')], max_length=1)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=8)),
                ('ciudad', models.CharField(choices=[('SANTIAGO', 'SANTIAGO'), ('VALPARÍSO', 'VALPARAÍSO'), ('CONCEPCIÓN', 'CONCEPCIÓN')], max_length=20)),
                ('direccion', models.CharField(max_length=75)),
                ('contraseña', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.juego')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='SuspenderUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_dias', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fsuspender_u', models.ImageField(upload_to='susp_user', verbose_name='Imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario'),
        ),
        migrations.AddField(
            model_name='juego',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario'),
        ),
        migrations.CreateModel(
            name='EliminarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('feliminar_u', models.ImageField(upload_to='del_user', verbose_name='Imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewebstore.usuario')),
            ],
        ),
    ]
